name: CI - Health Checks

on:
  push:
  pull_request:

jobs:
  health-checks:
    runs-on: ubuntu-latest

    env:
      DISK_THRESHOLD: 80
      MEM_THRESHOLD: 80

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use secret safely (masked)
        env:
          API_KEYS: ${{ secrets.FAKE_API_KEY }}
        run: |
          echo "API key lenght is: ${#API_KEY}"
          echo "API key starts with: ${API_KEY:0:4}****"

      - name: Make scripts executable
        run: chmod +x scripts/*.sh

      - name: Run disk check
        run: ./scripts/disk_check.sh

      - name: Run memory check
        run: ./scripts/memory_check.sh

